"""
finetune_llm.py — Fine-tune a small LLM on expert life support data
====================================================================
Uses LoRA (PEFT) + SFTTrainer (TRL) to fine-tune a small instruction-tuned
LLM on expert trajectories generated by the PPO agent.

RECOMMENDED USAGE:
  Local (if you have a GPU):
    python finetune_llm.py

  HuggingFace Spaces (recommended, uses your $30 credits):
    # This runs automatically in the Docker container

MODELS (choose based on your GPU):
  - Qwen/Qwen2.5-1.5B-Instruct  (default, ~3GB, fits T4 easily)
  - HuggingFaceTB/SmolLM2-1.7B-Instruct  (alternative)
  - meta-llama/Llama-3.2-1B-Instruct  (needs HF access approval)

Output:
  lifesupport-llm/         — merged fine-tuned model (ready to push to HF Hub)
  lifesupport-llm-lora/    — LoRA adapter only (lightweight)
"""

import argparse
import os
import torch
from datasets import load_dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
)
from peft import LoraConfig, get_peft_model, PeftModel
from trl import SFTTrainer, SFTConfig


def main():
    parser = argparse.ArgumentParser(
        description="Fine-tune a small LLM on expert life support data"
    )
    parser.add_argument("--base-model", default="Qwen/Qwen2.5-1.5B-Instruct",
                        help="Base model to fine-tune")
    parser.add_argument("--data-dir", default="expert_data",
                        help="Directory with expert_train.jsonl and expert_eval.jsonl")
    parser.add_argument("--output-dir", default="lifesupport-llm-lora",
                        help="Output directory for LoRA adapter")
    parser.add_argument("--merged-dir", default="lifesupport-llm",
                        help="Output directory for merged model")
    parser.add_argument("--epochs", type=int, default=3,
                        help="Number of training epochs")
    parser.add_argument("--batch-size", type=int, default=4,
                        help="Per-device training batch size")
    parser.add_argument("--grad-accum", type=int, default=4,
                        help="Gradient accumulation steps (effective batch = batch_size * grad_accum)")
    parser.add_argument("--lr", type=float, default=2e-4,
                        help="Learning rate")
    parser.add_argument("--max-seq-len", type=int, default=512,
                        help="Maximum sequence length")
    parser.add_argument("--lora-r", type=int, default=16,
                        help="LoRA rank")
    parser.add_argument("--lora-alpha", type=int, default=32,
                        help="LoRA alpha")
    parser.add_argument("--push-to-hub", action="store_true",
                        help="Push merged model to HuggingFace Hub")
    parser.add_argument("--hub-repo", default=None,
                        help="HuggingFace Hub repo name (e.g., 'username/lifesupport-llm')")
    parser.add_argument("--use-4bit", action="store_true",
                        help="Use 4-bit quantization (saves memory, needs bitsandbytes)")
    args = parser.parse_args()

    train_path = os.path.join(args.data_dir, "expert_train.jsonl")
    eval_path = os.path.join(args.data_dir, "expert_eval.jsonl")

    if not os.path.exists(train_path):
        print(f"\n  ERROR: No training data at {train_path}")
        print(f"  Generate first: python generate_expert_data.py --task task_medium --episodes 150\n")
        return

    print(f"\n{'='*62}")
    print(f"  LLM Fine-Tuning — Life Support Expert Distillation")
    print(f"  Base model : {args.base_model}")
    print(f"  LoRA rank  : {args.lora_r}")
    print(f"  Epochs     : {args.epochs}")
    print(f"  Batch size : {args.batch_size} × {args.grad_accum} = {args.batch_size * args.grad_accum}")
    print(f"  Max seq len: {args.max_seq_len}")
    print(f"{'='*62}\n")

    # ── Load dataset ─────────────────────────────────────────────────────────
    print("  Loading expert data...")
    dataset = load_dataset("json", data_files={
        "train": train_path,
        "eval": eval_path if os.path.exists(eval_path) else train_path,
    })
    print(f"  Train samples: {len(dataset['train'])}")
    print(f"  Eval samples:  {len(dataset['eval'])}")

    # ── Load tokenizer ───────────────────────────────────────────────────────
    print(f"\n  Loading tokenizer: {args.base_model}")
    tokenizer = AutoTokenizer.from_pretrained(
        args.base_model,
        trust_remote_code=True,
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"

    # ── Load model ───────────────────────────────────────────────────────────
    print(f"  Loading model: {args.base_model}")
    model_kwargs = {
        "trust_remote_code": True,
        "torch_dtype": torch.float16,
        "device_map": "auto",
    }

    if args.use_4bit:
        print("  Using 4-bit quantization (QLoRA)")
        model_kwargs["quantization_config"] = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.float16,
            bnb_4bit_use_double_quant=True,
        )

    model = AutoModelForCausalLM.from_pretrained(args.base_model, **model_kwargs)

    # ── LoRA config ──────────────────────────────────────────────────────────
    print(f"  Applying LoRA (r={args.lora_r}, alpha={args.lora_alpha})")
    lora_config = LoraConfig(
        r=args.lora_r,
        lora_alpha=args.lora_alpha,
        lora_dropout=0.05,
        bias="none",
        task_type="CAUSAL_LM",
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                        "gate_proj", "up_proj", "down_proj"],
    )

    # ── Training config ──────────────────────────────────────────────────────
    training_args = SFTConfig(
        output_dir=args.output_dir,
        num_train_epochs=args.epochs,
        per_device_train_batch_size=args.batch_size,
        per_device_eval_batch_size=args.batch_size,
        gradient_accumulation_steps=args.grad_accum,
        learning_rate=args.lr,
        lr_scheduler_type="cosine",
        warmup_steps=100,            # replaces deprecated warmup_ratio
        weight_decay=0.01,
        fp16=True,
        logging_steps=25,
        eval_strategy="steps",
        eval_steps=200,
        save_strategy="steps",
        save_steps=500,
        save_total_limit=2,
        packing=False,
        report_to="none",
        seed=42,
    )

    # ── Train ────────────────────────────────────────────────────────────────
    print("\n  Starting fine-tuning...\n")
    import inspect
    sft_params = inspect.signature(SFTTrainer.__init__).parameters

    trainer_kwargs = dict(
        model=model,
        args=training_args,
        train_dataset=dataset["train"],
        eval_dataset=dataset["eval"],
        peft_config=lora_config,
    )
    # trl >= 0.12 renamed 'tokenizer' to 'processing_class'
    if "processing_class" in sft_params:
        trainer_kwargs["processing_class"] = tokenizer
    elif "tokenizer" in sft_params:
        trainer_kwargs["tokenizer"] = tokenizer

    # max_seq_length was moved from SFTConfig to SFTTrainer in some versions
    if "max_seq_length" in sft_params:
        trainer_kwargs["max_seq_length"] = args.max_seq_len

    trainer = SFTTrainer(**trainer_kwargs)

    trainer.train()

    # Save LoRA adapter
    trainer.save_model(args.output_dir)
    tokenizer.save_pretrained(args.output_dir)
    print(f"\n  LoRA adapter saved → {args.output_dir}")

    # ── Merge LoRA into base model ───────────────────────────────────────────
    print(f"\n  Merging LoRA into base model...")
    
    # Reload base model in full precision for merging
    base_model = AutoModelForCausalLM.from_pretrained(
        args.base_model,
        trust_remote_code=True,
        torch_dtype=torch.float16,
        device_map="cpu",  # merge on CPU to avoid OOM
    )
    merged_model = PeftModel.from_pretrained(base_model, args.output_dir)
    merged_model = merged_model.merge_and_unload()

    merged_model.save_pretrained(args.merged_dir)
    tokenizer.save_pretrained(args.merged_dir)
    print(f"  Merged model saved → {args.merged_dir}")

    # ── Push to Hub ──────────────────────────────────────────────────────────
    if args.push_to_hub and args.hub_repo:
        print(f"\n  Pushing to HuggingFace Hub: {args.hub_repo}")
        merged_model.push_to_hub(args.hub_repo, token=os.getenv("HF_TOKEN"))
        tokenizer.push_to_hub(args.hub_repo, token=os.getenv("HF_TOKEN"))
        print(f"  ✓ Model pushed to https://huggingface.co/{args.hub_repo}")
        print(f"\n  Update inference.py:")
        print(f"    MODEL_NAME = \"{args.hub_repo}\"")
    else:
        print(f"\n  To push to HuggingFace Hub later:")
        print(f"    python finetune_llm.py --push-to-hub --hub-repo YOUR_USERNAME/lifesupport-llm")

    print(f"\n  ✓ Fine-tuning complete!")
    print(f"  Next steps:")
    print(f"    1. Push model:  set HF_TOKEN and use --push-to-hub --hub-repo USERNAME/lifesupport-llm")
    print(f"    2. Run inference: MODEL_NAME=USERNAME/lifesupport-llm python inference.py\n")


if __name__ == "__main__":
    main()
