name: Sync to Hugging Face
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        uses: huggingface/github-action@main
        with:
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_id: tsrinath/Scaler-Round-2
          repo_type: space
